<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 hero-slider-block">
<div class="col-xs-12 text-right">
	<span style="line-height: 30px;height: 30px;float: right;width: 100%;margin-right: 15px;">
		<span style="color:#FDC005; margin:0 10px"><img src="<?php echo $this->getSkinUrl('images/whatsapp.png'); ?>"></span>
		<b>7899777078</b>.. &nbsp; WhatsApp to Order Now !
	</span>

</div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-page-menu')->toHtml();?>
<!-- Carousel-->
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('new-home-slideshow')->toHtml();?>
<!-- /.carousel -->
</div>
</div>
