<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2008-2015 Diglin GmbH - Switzerland (http://www.diglin.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Mage_Customer_Block_Form_Register */
?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
    <div class="creat_account">
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="register">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

            <h2><?php echo $this->__('New Customers') ?></h2>
            <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>

            <ul>
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                <li>
                    <input type="text" placeholder="Email Address" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text" />
                </li>    
                    <!-- <input type="text" name="username" id="username" value="<?php //echo $this->escapeHtml($this->getFormData()->getUsername()) ?>" title="<?php //echo Mage::helper('username')->__('Username') ?>" class="input-text required-entry" /> -->
                       
                <li class="right">
                    <input type="text" name="mobile_code" id="mobile_code" value="<?php echo $this->htmlEscape($this->getFormData()->getMobileCode()) ?>" title="<?php echo $this->__('Country Code') ?>" class="input-text validate-digits" style="width:30px;" /> -
    
                        <input type="text" placeholder="Mobile No." name="mobile" id="mobile" value="<?php echo $this->htmlEscape($this->getFormData()->getMobile()) ?>" title="<?php echo $this->__('Mobile No.') ?>" class="input-text validate-digits" style="width:84%; float:right" /><br />
                            <em>The mobile number should be prefixed by the country code. E.g. 919820077777 where 91 is the country code. There should be no spaces, alphanumeric characters, zero prefixes or + sign or &#8211; sign in the mobile number.</em>
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li >
                    <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                </li>

                <?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            </ul>





    <?php if($this->getShowAddressFields()): ?>
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul >
                <li>
                    <input type="text" placeholder="Company" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                </li>
                <li class="right">
                    <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                </li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li>
                        <input type="text" placeholder="Street Address" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="right">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                </li>
            <?php endfor; ?>
                <li>
                    <input type="text" placeholder="City" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                </li>
                <li>
                    <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>
                    <script type="text/javascript">
                            //<![CDATA[
                        $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                    </script>
                    <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                </li>
                <li>
                    <input type="text" placeholder="Zip/Postal Code" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                </li>
                <li>
                    <?php echo $this->getCountryHtmlSelect() ?>>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />

    <?php endif; ?>


        
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <ul>
                <li>
                    <input type="password" placeholder="Password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                </li>
                <li class="right">
                    <input type="password" placeholder="Confirm Password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>

                <li>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </li>
                <li class="right">
                    <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><?php echo $this->__('Creat An Account') ?></span></button>
                </li>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

        </div>

        </form>



        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    
    </div>
</div>

<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
    <form action="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>customer/account/loginPost/" method="post" id="login-form">
            <div class="login_panel">
                <h2><?php echo $this->__('Registered Customers') ?></h2>
                <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                <ul>
                    <li>
                        <input type="text" name="login[username]" placeholder="* Mobile Number" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry" title="<?php echo $this->__('Mobile Number') ?>" />
                    </li>
                    <li>
                        <input type="password" name="login[password]" placeholder="* Password" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>"/>
                        <button type="submit" class="submit" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><img src="<?php echo $this->getSkinUrl('images/submit_arrow.jpg'); ?>" /></span></button>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                </ul>
                <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

                <span class="forget"><?php echo $this->__('* Required Fields') ?></span>
                <span class="forget"><a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a></span>

              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <span class="or"><img src="<?php //echo $this->getSkinUrl('images/or.jpg'); ?>" /></span>
                </div>
                <span class="col-lg-6 col-md-6 col-sm-12 col-xs-12"><a href="https://www.facebook.com/mSupplydotcom?fref=ts" target="_blank"><img src="<?php  echo $this->getChildHtml('inchoo_socialconnect_facebook_login_button'); ?>" /></a></span>
                <span class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   </span>
            </div>
    </form>
</div>



    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
