<?php
/**
 * Diglin GmbH
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    Diglin
 * @package     Diglin_Username
 * @copyright   Copyright (c) 2008-2015 Diglin GmbH (http://www.diglin.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *
 * Diglin GmbH - change the strings to add 'Username' information
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <!-- forgetblock end-->
    <div class="forgetcontainer">
        <div class="forgetblock">
    <div class="fieldset">
        <h2 class="retrtxt"><?php echo $this->__('Retrieve your password here') ?></h2>
        <p class="forgetpwdcmt"><?php echo Mage::helper('username')->__('Please enter your Mobile Number below. You will receive a link to reset your password.') ?></p>
        <ul class="form-cont">
            <li>
                
                <div class="input-box cinput">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry" placeholder="Enter Mobile Number" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
                </div>
            </li>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
    </div>
    <div class="fwdbutton-set">
        
        
        <button type="submit" title="<?php echo $this->__('Get My Password') ?>" class="fwdbtn"><span><span>Get My Password</span></span></button>
        <a title="<?php echo $this->__('Back to Login') ?>" href="<?php echo $this->helper('customer')->getLoginUrl() ?>" class="fwdbtn mr10"><?php echo $this->__('Back to Login') ?></a>
    </div>

</div><!-- forgetblock end-->
</div><!-- forgetcontainer end-->
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
