<?php if($this->getTitle()): ?>
<div class="page-title block-title title-create-address">
    <h1><?php echo $this->getTitle() ?></h1>
</div>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
<div class="welcome-msg"><span><?php echo $this->__('Contact Information') ?></span></div>
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
    <div class="add_contact">
        <?php if($this->getTitle()): ?>
		<div>
			<h2><?php echo $this->getTitle() ?></h2>
		</div>
		<?php endif; ?>  
        <ul>
			<h4>CONTACT INFORMATION</h4>
            <?php echo $this->getNameBlockHtml() ?>
			<!--<li><input placeholder="Company" type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" /></li>-->
			<li><input placeholder="* Telephone" type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="mobile input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" /></li>
			<!--<li><input placeholder="Fax" type="text" name="fax" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" /></li>-->
			<li><input type="text" placeholder="* Zip/Postal Code" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text required-entry validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" /></li>
			<li><p class="required"><?php echo $this->__('* Required Fields') ?></p></li>
        </ul>
        <ul> 
            <h4>ADDRESS</h4>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <li class="right">
                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" placeholder="* Street Address 1" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="street1 input-text <?php //echo $_streetValidationClass ?>" />
            </li>
				 <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
				<?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
			<li><input placeholder="Street Address 2" type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class=" street2 input-text <?php //echo $_streetValidationClass ?>" />
            </li>
				<?php endfor; ?>
				
				<?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
			<li><input type="text" placeholder="* VAT Number" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" id="vat_id" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
            </li>
				<?php endif; ?>
				
				<li><input type="text" placeholder="* City" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" /></li>
				<li>
                        <select id="region_id" placeholder="State/Province" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                           
							<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                        //<![CDATA[
                            $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                        //]]>
                        </script>
                        <input type="text" placeholder="* State/Province" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                </li>
		<li><input type="text" placeholder="* Zip/Postal Code" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text required-entry validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" /></li>
		<li><?php echo $this->getCountryHtmlSelect() ?></li>
        </ul>

            <div class="clearfix"></div>

        <ul>
			<li>
			<div <?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
                <?php if($this->isDefaultBilling()): ?>
                    <strong><?php echo $this->__('Default Billing Address') ?></strong>
                <?php elseif($this->canSetAsDefaultBilling()): ?>
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo $this->__('Use as My Default Billing Address') ?>" class="checkbox" /><label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_billing" value="1" />
                <?php endif; ?>
            </div>
            <div <?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
                <?php if($this->isDefaultShipping()): ?>
                    <strong><?php echo $this->__('Default Shipping Address') ?></strong>
                <?php elseif($this->canSetAsDefaultShipping()): ?>
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo $this->__('Use as My Default Shipping Address') ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                <?php else: ?>
                    <input type="hidden" name="default_shipping" value="1" />
                <?php endif; ?>
			</div>	
            </li>
        </ul>
        <ul>
			<li class="right"><button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><?php echo $this->__('Save') ?></span></button></li>
        </ul>
    </div>
  
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
   // new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
 new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
//]]>

	jQuery(document).ready(function() {

		jQuery('#form-validate').click(function() { 
		
			/// *** First name validate *** ///
			
			jQuery(".error1").hide();
			var hasError1 = false;
			var nameregex =/^[a-zA-Z. ]+$/;
			var nameaddressVal = jQuery("#firstname").val();
			if(!nameregex.test(nameaddressVal)) {
					jQuery("#firstname").after('<span style="color:#ec5523;" class="error1">Enter Valid First Name.</span>');
					hasError1 = true;
				}

			if(hasError1 == true) { return false; }
			
			/// *** Last name validate *** ///
			
			jQuery(".error2").hide();
			var hasError2 = false;
			var lnameregex =/^[a-zA-Z. ]+$/;
			var lnameaddressVal = jQuery("#lastname").val();
			if(!lnameregex.test(lnameaddressVal)) {
					jQuery("#lastname").after('<span style="color:#ec5523;" class="error2">Enter Valid Last Name.</span>');
					hasError2 = true;
				}

			if(hasError2 == true) { return false; }
			
			/// *** Address 1 validate *** ///
			
			jQuery(".error3").hide();
			var hasError3 = false;
			var addressregex =/^[a-zA-Z0-9\/\-.,#_ ]+$/i;
			var addressVal = jQuery(".street1").val();
			if(!addressregex.test(addressVal)) {
					jQuery(".street1").after('<span style="color:#ec5523;" class="error3">Enter Valid Address.</span>');
					hasError3 = true;
			}

			/// *** Address 2 validate *** ///
			
			jQuery(".error4").hide();
			var hasError4 = false;
			var address2regex = /^[a-zA-Z0-9\/\-.,#_ ]+$/i;
			var address2Val = jQuery(".street2").val();
			if(!address2regex.test(address2Val)) {
					jQuery(".street2").after('<span style="color:#ec5523;" class="error4">Enter Valid Address.</span>');
					hasError4 = true;
			}
			
			/// *** Mobile validate *** ///
			
			jQuery(".error5").hide();
			var hasError5 = false;
			var mobiReg = /^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$/;
			var mobileVal = jQuery(".mobile").val();
			var data =jQuery(".mobile").val();
			
			/** 5 number validation **/
			var mobi5first = data.substring(0,5);
			var mobi5second = data.substring(5,10);

			 /** 4 number validation **/
			var mobi4first = data.substring(0,4);
			var mobi4second = data.substring(4,8);

			/** 3 number validation **/
			var mobi3first = data.substring(0,3);
			var mobi3second = data.substring(3,6);
			var mobi3third = data.substring(6,9);
					 
			if(mobileVal == '') {
				jQuery(".mobile").after('<span style="color:#ec5523;" class="error5">Enter Mobile Number.</span>');
				hasError5 = true;
			}

			else if(!mobiReg.test(mobileVal)) {
				jQuery(".mobile").after('<span style="color:#ec5523;" class="error5">Enter Valid Mobile Number.</span>');
				hasError5 = true;
			}
			
			else if((mobi5first == 99999 || mobi5first == 88888 || mobi5first == 77777) || (mobi5second == 00000 || mobi5second == 11111 || mobi5second == 22222 || mobi5second == 33333 || mobi5second == 44444 || mobi5second == 55555 || mobi5second == 66666 || mobi5second == 77777 || mobi5second == 88888 || mobi5second == 99999))
			 {
				jQuery(".mobile").after('<span style="color:#ec5523;" class="error5">Enter Valid Mobile Number.</span>');
				hasError5 = true;	 
			 }
			  else if((mobi4first == 9999 || mobi4first == 8888 || mobi4first == 7777) || (mobi4second == 0000 || mobi4second == 1111 || mobi4second == 2222 || mobi4second == 3333 || mobi4second == 4444 || mobi4second == 5555 || mobi4second == 6666 || mobi4second == 7777 || mobi4second == 8888 || mobi4second == 9999))
			 {
				jQuery(".mobile").after('<span style="color:#ec5523;" class="error5">Enter Valid Mobile Number.</span>');
				 hasError5 = true;	 
			 }
			 
			else if ((mobi3first == 999 || mobi3first == 888 || mobi3first == 777) && (mobi3second == 000 || mobi3second == 111 || mobi3second == 222 || mobi3second == 333 || mobi3second == 444 || mobi3second == 555 || mobi3second == 666 || mobi3second == 777 || mobi3second == 888 || mobi3second == 999) && (mobi3third == 000 || mobi3third == 111 || mobi3third == 222 || mobi3third == 333 || mobi3third == 444 || mobi3third == 555 || mobi3third == 666 || mobi3third == 777 || mobi3third == 888 || mobi3third == 999))
			 {
					jQuery(".mobile").after('<span style="color:#ec5523;" class="error5">Enter Valid Mobile Number.</span>');
					hasError5 = true;	 
			 }
			
			if(hasError5 == true) { return false; }
			
			/// *** Zip/Postal Validate *** ///
			
			jQuery(".error6").hide();
			var hasError6 = false;
			var zipcodestart= 560000;
			var zipcodeend = 560300;
			
			var zipcodekVal = jQuery("#zip").val();
	
			if(zipcodekVal == '') {
				jQuery("#zip").after('<span class="error6">Enter Zip Code.</span>');
				hasError6 = true;
			}
			else if(!(zipcodekVal > zipcodestart && zipcodekVal < zipcodeend)) {
				jQuery("#zip").after('<span class="error6">Enter Only Bangalore Zip Code.</span>');
				hasError6 = true;
				
			} 
			if(hasError6 == true) { return false; }
			
		});
   
	});

</script>
