<?php

/*------------------------------------------------------------------------

 # SM Basic Products - Version 1.0.0

 # Copyright (c) 2014 YouTech Company. All Rights Reserved.

 # @license - Copyrighted Commercial Software

 # Author: YouTech Company

 # Websites: http://www.magentech.com

-------------------------------------------------------------------------*/

$list = $this->_getProducts();

$helper = Mage::helper('basicproducts/data');

if (!empty($list)) {

	$uniqued = 'sm_basic_products_' . time() . rand();



	$class_respl = 'bs-resp01-' . $this->_getConfig('nb_column1', 6) . ' bs-resp02-' . $this->_getConfig('nb_column2', 4) . ' bs-resp03-' . $this->_getConfig('nb_column3', 2) . ' bs-resp04-' . $this->_getConfig('nb_column4', 1);



	?>



<?php

} else {

	echo 'Has no content to show!';

}?>

<?php /*

if(Mage::registry('current_category')){?>

<div class="categoryfaq">

<div class="block-title"><span>FAQ</span></div>

<?php $catID = Mage::getSingleton('catalog/layer')->getCurrentCategory()->getId();?>

<div class="sm-basic-products">

<p><?php echo Mage::getResourceModel('catalog/category')->getAttributeRawValue($catID, "faq", Mage::app()->getStore()->getId());?></p>

</div>

</div>

<?php }*/?>