<ul class="nav nav-tabs cpaymenttab" role="tablist">
    <li role="presentation"><a href="#Address" aria-controls="home" role="tab" data-toggle="tab">Billing Address</a></li>
	<li role="presentation" class="active"><a href="#Address" aria-controls="home" role="tab" data-toggle="tab">Shipping Address</a></li>
    <li role="presentation"><a href="#Payment" aria-controls="messages" role="tab" data-toggle="tab">Payment</a></li>
    <li role="presentation"><a href="#Complete" aria-controls="settings" role="tab" data-toggle="tab">Complete</a></li>
</ul>
<form action="" id="co-shipping-form">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mt20 pad10">
    <div class="ship-address form-list">
       <?php if ($this->customerHasAddresses()): ?>
       <div class="field">
                    
           <div class="input-box">
               <?php echo $this->getAddressesHtmlSelect('shipping') ?>
           </div>
       </div>
    <?php endif ?>
	<div class="field" id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
        <div class="input-box">
            <fieldset>
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                
                    <div class="field">
                        <div class="input-box">
    					<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
                        </div>
                    </div>

                    <div>
                        <input type="text" placeholder="Company" "id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <div>
                        <input type="text"  placeholder="*<?php echo $this->__('Address') ?>" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <div>
                        <input type="text" placeholder="Address <?php echo $_i; ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                    <?php endfor; ?>
                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                    <div>
                        <input type="text" placeholder="<?php echo $this->__('VAT Number'); ?>" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                    </div>
                    <?php endif; ?>
                    <div>
                        <input type="text" placeholder="*<?php echo $this->__('City') ?>" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="Bangalore" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?> cityy" id="shipping:city" onchange="shipping.setSameAsBilling(false);" readonly="readonly" />
                    </div>
                    <div>
                        <select id="shipping:region_id" placeholder="*<?php echo $this->__('State/Province') ?>" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select statee" style="display:none;" disabled>
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                        <input type="text"  placeholder="*<?php echo $this->__('State/Province') ?>" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?> statee" style="display:none;" />
                    </div>
                    <div>
                        <input type="text" placeholder="*<?php echo $this->__('Zip/Postal Code') ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
                    <div>
                    <div>
                        <?php echo $this->getCountryHtmlSelect('shipping') ?>
                    </div>
                    <div>
                        <input type="text" placeholder="*<?php echo $this->__('Telephone') ?>" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                    <div>
                        <input type="text" placeholder="<?php echo $this->__('Fax') ?>" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <div>
                    <div class="full-ship-yes">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></div></div>
                <?php else:?>
                    <input type="hidden" name="shipping[save_in_address_book]" value="1" />
                <?php endif;?>
                </ul>
            </fieldset>
        </div>
    </div>

    <div style="display:none;">
        <div class="full-ship-me">
            <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
        </div>
    </div>
    
    <div class="buttons-set" id="shipping-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="button" class="savebtn check_shipping" title="<?php echo $this->__('Save and Continue') ?>"><span><span><?php echo $this->__('Save and Continue') ?></span></span></button>
        <span id="shipping-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
    </div>
</div>
</form>




<script type="text/javascript">
//<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script>


<script type="text/javascript">
jQuery(".statee").val('501');
jQuery("#shipping-address-select").val("");
jQuery("#shipping-new-address-form").css("display", "block");

jQuery(".check_shipping").click(function(){
cityy = jQuery(".cityy").val();
statee = jQuery(".statee").val();
if(cityy == 'Bangalore' || cityy == 'bangalore' && statee == 501)
{
shipping.save();	
}	
else
{
alert("Currently delivering in Bangalore only.");	
}	
});
</script>
