<script type="text/javascript">
//<![CDATA[
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    var lastPrice;
//]]>
</script>
<ul class="nav nav-tabs cpaymenttab" role="tablist">
    <li role="presentation"><a href="#Address" aria-controls="home" role="tab" data-toggle="tab">Billing Address</a></li>
    <li role="presentation"><a href="#Address" aria-controls="home" role="tab" data-toggle="tab">Shipping Address</a></li>
    <li role="presentation" class="active"><a href="#Payment" aria-controls="messages" role="tab" data-toggle="tab">Payment</a></li>
    <li role="presentation"><a href="#Complete" aria-controls="settings" role="tab" data-toggle="tab">Complete</a></li>
</ul>
<form action="" id="co-payment-form">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mt20 pad10">
        <div class="ship-address form-list">
            <?php echo $this->getChildHtml('methods') ?>
        </div>
    </div>
</form>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
<div class="buttons-set" id="payment-buttons-container">
   <!-- <p class="required"><?php echo $this->__('* Required Fields') ?></p>-->
    
    <button type="button" class="savebtn savebtn-right" onclick="payment.save()"><span><span><?php echo $this->__('Save and Continue') ?></span></span></button>
	<p class="chq-or"><?php echo $this->__('OR') ?></p>
	<p class="back-link back-link-right">  <a href="#" onclick="checkout.back(); return false;"><?php echo $this->__('Go Back') ?></a></p>
    <span class="please-wait" id="payment-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>
<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-560)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
//]]>
</script>
