<ul class="nav nav-tabs cpaymenttab" role="tablist">
    <li role="presentation"><a href="#Address" aria-controls="home" role="tab" dataship-toggle="tab">Billing Address</a></li>
	<li role="presentation" class="active"><a href="#Address" aria-controls="home" role="tab" dataship-toggle="tab">Shipping Address</a></li>
    <li role="presentation"><a href="#Payment" aria-controls="messages" role="tab" dataship-toggle="tab">Payment</a></li>
    <li role="presentation"><a href="#Complete" aria-controls="settings" role="tab" dataship-toggle="tab">Complete</a></li>
</ul>
<form action="" id="co-shipping-form">
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mt20 pad10">
    <div class="ship-address form-list">
       <?php if ($this->customerHasAddresses()): ?>
       <div class="field">
                    
           <div class="input-box">
               <?php echo $this->getAddressesHtmlSelect('shipping') ?>
           </div>
       </div>
    <?php endif ?>
	<div class="field" id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
        <div class="input-box">
            <fieldset>
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                
                    <div class="field">
                        <div>
    					<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
                        </div>
                    </div>

                    <!--<div>
                        <input type="text" placeholder="Company" "id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
                    </div>-->
                    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <div>
                        <input type="text"  placeholder="*<?php echo $this->__('Address') ?>" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text streetship1 <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <div>
                        <input type="text" placeholder="Address <?php echo $_i; ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text streetship2 <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                    <?php endfor; ?>
                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                    <div>
                        <input type="text" placeholder="<?php echo $this->__('VAT Number'); ?>" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                    </div>
                    <?php endif; ?>
                    <div>
                        <input type="text" placeholder="*<?php echo $this->__('City') ?>" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="Bangalore" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?> cityy" id="shipping:city" onchange="shipping.setSameAsBilling(false);" readonly="readonly" />
                    </div>
                    <div>
                        <select id="shipping:region_id" placeholder="*<?php echo $this->__('State/Province') ?>" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select statee" style="display:none;" disabled>
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![Cdataship[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                        <input type="text"  placeholder="*<?php echo $this->__('State/Province') ?>" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?> statee" style="display:none;" />
                    </div>
                    <div>
                        <input id="zip" type="text" placeholder="*<?php echo $this->__('Zip/Postal Code') ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()); ?>" class="input-text required-entry maximum-length-6 minimum-length-6 validate-digits validate-length zipship <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
                    <div>
					
                    <div>
                        <?php echo $this->getCountryHtmlSelect('shipping') ?>
                    </div>
                    <div>
                        <input type="text" placeholder="*<?php echo $this->__('Telephone') ?>" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="mobileship input-text required-entry maximum-length-10 minimum-length-10 validate-digits validate-length <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                   <!-- <div>
                        <input type="text" placeholder="<?php echo $this->__('Fax') ?>" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
                    </div>-->
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <div>
                    <div class="full-ship-yes">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></div></div>
                <?php else:?>
                    <input type="hidden" name="shipping[save_in_address_book]" value="1" />
                <?php endif;?>
                </ul>
            </fieldset>
        </div>
    </div>

    <div style="display:none;">
        <div class="full-ship-me">
            <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
        </div>
    </div>
    
    <div class="buttons-set" id="shipping-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="button" class="savebtn check_shipping" title="<?php echo $this->__('Save and Continue') ?>"><span><span><?php echo $this->__('Save and Continue') ?></span></span></button>
        <span id="shipping-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
    </div>
</div>
</form>




<script type="text/javascript">
//<![Cdataship[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
//]]>
</script>
<style>.error{color:red;}.error1ship{color:red;}.error2ship{color:red;}.error3ship{color:red;}.error4ship{color:red;}.error5ship{color:red;}.error6ship{color:red;}</style>

<script type="text/javascript">
jQuery(".statee").val('501');
jQuery("#shipping-address-select").val("");
jQuery("#shipping-new-address-form").css("display", "block");



jQuery(".check_shipping").click(function(){

jQuery('.statee').val('501').attr("selected", "selected");	
cityy = jQuery(".cityy").val();
statee = jQuery(".statee").val();

if(cityy == 'Bangalore' || cityy == 'bangalore' && statee == 501)
{

	var hasErrorship1 = false; 
	var mobiRegship = /^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$/;
	//var mobiRegship1 = /^(?:[2-9][0-8][0-9])(?!(\d)\1+$)([2-9][0-9]{2}[0-9]{4})$/;
	jQuery(".error1ship").hide();
	var mobileshipshipVal = jQuery(".mobileship").val();
	
	var dataship =jQuery(".mobileship").val();
	
	/** 5 number validation **/
    var mobi5shipfirst = dataship.substring(0,5);
	var mobi5shipsecond = dataship.substring(5,10);

	 /** 4 number validation **/
	var mobi4shipfirst = dataship.substring(0,4);
	var mobi4shipsecond = dataship.substring(4,8);

	/** 3 number validation **/
    var mobi3shipfirst = dataship.substring(0,3);
	var mobi3shipsecond = dataship.substring(3,6);
	var mobi3shipthird = dataship.substring(6,9);
	 
	
	 
    if(mobileshipshipVal == '') {
        jQuery(".mobileship").after('<span class="error1ship">Enter mobile number.</span>');
        hasErrorship1 = true;
    }

    else if(!mobiRegship.test(mobileshipshipVal)) {
        jQuery(".mobileship").after('<span class="error1ship">Enter Valid mobile Number.</span>');
        hasErrorship1 = true;
    }
	// else if(!mobiRegship1.test(mobileshipshipVal)) {
        // jQuery(".mobileship").after('<span class="error1ship">Enter a valid mobileship number wrong.</span>');
        // haserror1ship = true;
    // }
	
	 else if((mobi5shipfirst == 99999 || mobi5shipfirst == 88888 || mobi5shipfirst == 77777) || (mobi5shipsecond == 00000 || mobi5shipsecond == 11111 || mobi5shipsecond == 22222 || mobi5shipsecond == 33333 || mobi5shipsecond == 44444 || mobi5shipsecond == 55555 || mobi5shipsecond == 66666 || mobi5shipsecond == 77777 || mobi5shipsecond == 88888 || mobi5shipsecond == 99999))
     {
		jQuery(".mobileship").after('<span class="error1ship">Enter Valid mobile Number.</span>');
		hasErrorship1 = true;	 
	 }
	  else if((mobi4shipfirst == 9999 || mobi4shipfirst == 8888 || mobi4shipfirst == 7777) || (mobi4shipsecond == 0000 || mobi4shipsecond == 1111 || mobi4shipsecond == 2222 || mobi4shipsecond == 3333 || mobi4shipsecond == 4444 || mobi4shipsecond == 5555 || mobi4shipsecond == 6666 || mobi4shipsecond == 7777 || mobi4shipsecond == 8888 || mobi4shipsecond == 9999))
     {
		jQuery(".mobileship").after('<span class="error1ship">Enter Valid mobile Number.</span>');
		 hasErrorship1 = true;	 
	 }
	 
	else if ((mobi3shipfirst == 999 || mobi3shipfirst == 888 || mobi3shipfirst == 777) && (mobi3shipsecond == 000 || mobi3shipsecond == 111 || mobi3shipsecond == 222 || mobi3shipsecond == 333 || mobi3shipsecond == 444 || mobi3shipsecond == 555 || mobi3shipsecond == 666 || mobi3shipsecond == 777 || mobi3shipsecond == 888 || mobi3shipsecond == 999) && (mobi3shipthird == 000 || mobi3shipthird == 111 || mobi3shipthird == 222 || mobi3shipthird == 333 || mobi3shipthird == 444 || mobi3shipthird == 555 || mobi3shipthird == 666 || mobi3shipthird == 777 || mobi3shipthird == 888 || mobi3shipthird == 999))
	 {
			jQuery(".mobileship").after('<span class="error1ship">Enter Valid mobile Number.</span>');
			hasErrorship1 = true;	 
	 }else
	{
	jQuery(".error1ship").hide();	
	}
		 
		 
				jQuery(".error2ship").hide();
				var haserror2ship = false;
				var zipcodestartship= 560000;
				var zipcodeendship = 560300;
				
				var zipcodekValship = jQuery(".zipship").val();
		
				if(zipcodekValship == '') {
					jQuery(".zipship").after('<span class="error2ship">Enter Zip Code.</span>');
					haserror2ship = true;
				}
				else if(!(zipcodekValship > zipcodestartship && zipcodekValship < zipcodeendship)) {
					jQuery(".zipship").after('<span class="error2ship">Enter Bangalore Zip Code.</span>');
					haserror2ship = true;
					
				} 
	
	
		 
				jQuery(".error3ship").hide();
					var haserror3ship = false;
					var nameregexship =/^[a-zA-Z. ]+$/;
					var nameaddressValship = jQuery(".myfirstnameship").val();
					
					if(!nameregexship.test(nameaddressValship)) {
							jQuery(".myfirstnameship").after('<span class="error3ship">Enter Valid First Name.</span>');
							haserror3ship = true;
				}else{
				jQuery(".error3ship").hide();	
				}
				
				
				jQuery(".error4ship").hide();
					var haserror4ship = false;
					var addressregexship =/^[a-zA-Z0-9\/\-.,#_ ]+$/i;
					var addressValship = jQuery(".streetship1").val();
					if(!addressregexship.test(addressValship)) {
							jQuery(".streetship1").after('<span class="error4ship">Enter Valid Address.</span>');
							haserror4ship = true;
				}
				else
				{
					jQuery(".error4ship").hide();	
				}
					
				jQuery(".error5ship").hide();
				var haserror5ship = false;
				var lnameregexship =/^[a-zA-Z. ]+$/;
				var lnameaddressValship = jQuery(".mysecnameship").val();
				if(!lnameregexship.test(lnameaddressValship)) {
						jQuery(".mysecnameship").after('<span class="error5ship">Enter Valid Last Name.</span>');
						haserror5ship = true;
					}
					else{
					jQuery(".error5ship").hide();	
					}
				
				
        
				var address2Valshipemty = jQuery(".streetship2").val();
				
				if(!address2Valshipemty == ''){
					
					
					jQuery(".error6ship").hide();
						var haserror6ship = false;
						var address2regexship = /^[a-zA-Z0-9\/\-.,#_ ]+$/i;
						var address2Valship = jQuery(".streetship2").val();
						if(!address2regexship.test(address2Valship)) {
								jQuery(".streetship2").after('<span class="error6ship">Enter Valid Address.</span>');
								haserror6ship = true;
					}
					else
					{
					jQuery(".error6ship").hide();	
					}
					if(haserror6ship == true) { return false; }
				}
      

			
		 
		 if(hasErrorship1 == true)
		 {
			return false; 
		 }
         else if(haserror2ship == true)
         {
			return false;
		 }
		 else if(haserror3ship == true)
         {
			return false;
		 }
		 else if(haserror4ship == true)
         {
			return false;
		 }
		 else if(haserror5ship == true)
         {
			return false;
		 }
		 else
		 {
		 shipping.save();		 
		 }		 	
}	
else
{
alert("Currently delivering in Bangalore only.");	
}
	
});



</script>

