<?php
/*------------------------------------------------------------------------
 # SM Shop By - Version 1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<?php if ($this->canShowBlock()): ?>
    <?php if (!$this->getRequest()->isAjax()): ?>
    <div id="layered-navigation">
    <?php endif; ?>
        <div class="block block-layered-nav">
            <div class="block-title">
                <strong><span><?php echo $this->__('Shop By') ?></span></strong>
            </div>
            <?php if($this->getStateHtml()) { ?>
            <div class="currently-wrap">
                <?php echo $this->getStateHtml() ?>

                <?php if ($this->getLayer()->getState()->getFilters()): ?>
                    <div class="actions"><a class="button" href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
                <?php endif; ?>
            </div>
            <?php } ?>
            <div class="block-content">
                            
                <?php if ($this->canShowOptions()): ?>
                    <!--<p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>-->
                    <dl id="narrow-by-list">
                        <?php $_filters = $this->getFilters() ?>
                        <?php foreach ($_filters as $_filter): ?>
                            <?php if ($_filter->getItemsCount()): ?>
							<?php $cid =  Mage::getSingleton('catalog/layer')->getCurrentCategory()->getId(); ?>
							<?php if($cid == 189){ ?>
							<?php $filtername = $_filter->getName();
							if($filtername == 'Brand' || $filtername == 'Size' || $filtername == 'Price'){ ?>
							<?php //echo $this->__($_filter->getName()) ?>
                                <dt class="<?php echo $this->__($_filter->getName()) ?>"><?php echo $this->__($_filter->getName()) ?></dt>
								
                                <dd><?php echo $_filter->getHtml() ?></dd>
								<?php } ?>
								<?php }elseif($cid == 188){ ?>
							<?php $filtername = $_filter->getName();
							if($filtername == 'Brand' || $filtername == 'Price' || $filtername == 'Size'){ ?>
							
                                <dt class="<?php echo $this->__($_filter->getName()) ?>"><?php echo $this->__($_filter->getName()) ?></dt>
								
                                <dd><?php echo $_filter->getHtml() ?></dd>
								<?php } ?>
							<?php }else if($cid == 154){ ?>
							<?php $filtername = $_filter->getName();
							if($filtername == 'Brand' || $filtername == 'Price' || $filtername == 'Grade' || $filtername != 'Color' ){ ?>
							
                                <dt class="<?php echo $this->__($_filter->getName()) ?>"><?php echo $this->__($_filter->getName()) ?></dt>
								
                                <dd><?php echo $_filter->getHtml() ?></dd>
								<?php } ?>
							<?php }else if($cid == 155){ ?>
							<?php $filtername = $_filter->getName();
							if($filtername == 'Brand' || $filtername == 'Price' || $filtername == 'Grade' || $filtername == 'Diameter' || $filtername == 'Length'){ ?>
							
                                <dt class="<?php echo $this->__($_filter->getName()) ?>"><?php echo $this->__($_filter->getName()) ?></dt>
								
                                <dd><?php echo $_filter->getHtml() ?></dd>
								<?php } ?>
							<?php }else if($cid == 156){ ?>
							<?php $filtername = $_filter->getName();
							if($filtername == 'Brand' || $filtername == 'Price'){ ?>
				
                                <dt class="<?php echo $this->__($_filter->getName()) ?>"><?php echo $this->__($_filter->getName()) ?></dt>
								
                                <dd><?php echo $_filter->getHtml() ?></dd>
								<?php } ?>
							<?php }else if($cid == 160){ ?>
							<?php $filtername = $_filter->getName();
							if($filtername == 'Brand' || $filtername == 'Price' || $filtername == 'Size'){ ?>
                                <dt class="<?php echo $this->__($_filter->getName()) ?>"><?php echo $this->__($_filter->getName()) ?></dt>
								
                                <dd><?php echo $_filter->getHtml() ?></dd>
								<?php } ?>
							<?php }else if($cid == 163){ ?>
							<?php $filtername = $_filter->getName();
							if($filtername == 'Grade' || $filtername == 'Price'){ ?>
                                <dt class="<?php echo $this->__($_filter->getName()) ?>"><?php echo $this->__($_filter->getName()) ?></dt>
								
                                <dd><?php echo $_filter->getHtml() ?></dd>
								<?php } ?>
							<?php }else if($cid == 180){ ?>
							<?php $filtername = $_filter->getName();
							if($filtername == 'Brand' || $filtername == 'Size' || $filtername == 'Color' || $filtername == 'Price' || $filtername == 'Perforated Blocks'){ ?>
                                <dt class="<?php echo $this->__($_filter->getName()) ?>"><?php echo $this->__($_filter->getName()) ?></dt>
								
                                <dd><?php echo $_filter->getHtml() ?></dd>
								<?php } ?>
							<?php }else{ ?>
							<?php $filtername = $_filter->getName();
							if($filtername == 'Brand' || $filtername == 'Price' || $filtername == 'Type'){ ?>
                                <dt class="<?php echo $this->__($_filter->getName()) ?>"><?php echo $this->__($_filter->getName()) ?></dt>
								
                                <dd><?php echo $_filter->getHtml() ?></dd>
								<?php } ?>
							<?php } ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </dl>
                    <script type="text/javascript">decorateDataList('narrow-by-list')</script>
                <?php endif; ?>
            
                <?php /*if ($this->getLayer()->getState()->getFilters()): ?>
                    <div class="actions"><a class="button" href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
                <?php endif;*/ ?>
                
            </div>
        </div>
    <?php if (!$this->getRequest()->isAjax()): ?>
    </div>
    <?php endif; ?>
<?php endif; ?>
