<form id="discount-coupon-form"	 action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post"> 
    <div class="discount">
        <h2	><?php echo $this->__('Apply Coupon Code') ?></h2> 
<hr>		
        <div class="discount-form	col-lg-12 col-md-12 col-sm-12 col-xs-12 pad0 mt1em">
            <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
            <div class="coupon-box">
			
                 <input class="input-text" id="coupon_code" placeholder="your coupon code" 	name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" /> 
				
				 <input type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button apply_code" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"/>
				
            </div>
			
            <div class="buttons-set">
                <?php if(strlen($this->getCouponCode())): ?>
                    &nbsp; <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel Coupon') ?></span></span></button>
                <?php endif;?>
            </div>
        </div>
    </div>
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pad0 mt1em">
		
			<a class="mt5 contshop-btn"  title="<?php echo $this->__('Continue Shopping') ?>" href="<?php echo Mage::getBaseUrl(); ?>"><span class="button btn-checkout"><?php echo $this->__('Continue Shopping') ?></span></a>
	</div>
</form>

<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
