<?php
    $APIURL = Mage::getStoreConfig('configuration/configuration_homepage/homepageproductsapiurl')."newProducts";
    $ch = curl_init($APIURL);
	curl_setopt($ch, CURLOPT_URL,$APIURL);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $NewProducts=json_decode(curl_exec($ch));
	curl_close($ch);
    
    $APIURL = Mage::getStoreConfig('configuration/configuration_homepage/homepageproductsapiurl')."bestSeller";
    $ch = curl_init($APIURL);
	curl_setopt($ch, CURLOPT_URL,$APIURL);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $BestSellers=json_decode(curl_exec($ch));
	curl_close($ch);

    /*$APIURL = "http://52.30.181.28:3000/products/gethomepageproducts/comingSoon";
    $ch = curl_init($APIURL);
	curl_setopt($ch, CURLOPT_URL,$APIURL);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $ComingSoon=json_decode(curl_exec($ch));
	curl_close($ch);*/

    $liClasses = array ("col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider hidden-xs",                        
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider hidden-xs",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider",
                        "col-lg-2 col-md-2 col-sm-2 col-xs-6 divider hidden-xs");
                       
    
?>
<!-- msupply products container starts here -->
<style>.hmptitleblock { text-overflow: ellipsis;white-space: nowrap;width: 90%;overflow: hidden;}.hmptitle:hover{color: #637078 !important; text-decoration:none; cursor:pointer;}</style>
<div id="msupply_products">
      <div class="container mobile_align">
        <!-- msupply products  -->
        <div id="produts_nav">
          <!-- products nav section starts here -->
         <div class="centered col-xs-12" id="products_section">
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-3"> </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12" id="products_1"> <a href="javascript:void(0)">New Products </a> </div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12" id="products_2"> <a href="javascript:void(0)">Best Sellers </a> </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12" id="products_3"> <a href="javascript:void(0)">Coming Soon </a> </div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12"> </div>
          </div>
          <!-- products nav section end here -->
          <select id="drop_down">
            <option value="products_lists_2">Best Sellers</option>
            <option value="products_lists_1">New Products</option>
            <option value="products_lists_3">Coming Soon</option>
          </select>
          <!-- products items section(New Arrivals) starts here -->
          <div id="myCarousel" class="carousel slide">
            <div id="products_lists_1" class="carousel-inner">
              <!-- carousel item active starts -->
              <div class="item active">
                <ul class="row list_produtcs" id="products_items">
                    <?php
                        for($i=0;$i<5;$i++)
                        {
                     ?>
                            <li class="<?php echo $liClasses[$i]; ?>">
                            <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$NewProducts->products[$i]->request_path; ?>">
                                <img src="<?php echo $NewProducts->products[$i]->ImageURL; ?>" alt="msupply" width="170" height="235"/>
                            </a>
                            <!--<div><?php echo $NewProducts->products[$i]->Product_Name; ?></div>-->
                            <div class="hmptitleblock"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$NewProducts->products[$i]->request_path; ?>" class="hmptitle" title="<?php echo $NewProducts->products[$i]->Product_Name;  ?>"> <?php echo $NewProducts->products[$i]->Product_Name; ?></a></div>
                            <div class="price_tag wishlist_price">                                         
								<?php if($NewProducts->products[$i]->Special_Price !=''){ ?>	
								<span class="old-price">
									<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Price,'0'); ?>
								</span> 
								<?php
									$date = date("Y-m-d");
									if($NewProducts->products[$i]->Special_Price_From_Date !='' && $NewProducts->products[$i]->Special_Price_From_Date >= $date )
									{
										$date1=date_create($NewProducts->products[$i]->Special_Price_From_Date);
										$date2=date_create($NewProducts->products[$i]->Special_Price_To_Date);
										$diff=date_diff($date1,$date2);
										$sign = $diff->format("%R");
										$days = $diff->format("%a");
										if($sign == '+' && $days >= 0)
										{ ?>
											<span class="special-price"> <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Special_Price,'0'); ?> </span>
								 <?php 	}
									} else if($NewProducts->products[$i]->Special_Price_From_Date =='' && $NewProducts->products[$i]->Special_Price_To_Date =='' ){
								 ?>									
									<span class="special-price"> <?php  echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Special_Price,'0'); ?></span>
								<?php }
								}else { ?>
									<span class="regular-price">
										<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Price,'0'); ?>
									</span>
								<?php }	?>
								<?php 
									  if($NewProducts->products[$i]->Product_Unit != "")
									   echo " / ".$NewProducts->products[$i]->Product_Unit;
								?>
                            </div>
                          </li>
                    <?php
                                
                        }
                    ?>
                  </ul>
              </div>
              <!-- carousel item active  end here-->
			  
              <!-- carousel item  starts here-->
              <div class="item ">
                <ul class="row list_produtcs" id="products_items">
                  <?php
                        for($i=5;$i<10;$i++)
                        {
                     ?>
                            <li class="<?php echo $liClasses[$i]; ?>">
                            <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$NewProducts->products[$i]->request_path; ?>">
                                <img src="<?php echo $NewProducts->products[$i]->ImageURL; ?>" alt="msupply" width="170" height="235"/>
                            </a>
                            <!--<div><?php echo $NewProducts->products[$i]->Product_Name; ?></div>-->
                            <div class="hmptitleblock"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$NewProducts->products[$i]->request_path; ?>" class="hmptitle" title="<?php echo $NewProducts->products[$i]->Product_Name;  ?>"> <?php echo $NewProducts->products[$i]->Product_Name; ?></a></div>
                            <div class="price_tag wishlist_price">                                         
								<?php if($NewProducts->products[$i]->Special_Price !=''){ ?>	
								<span class="old-price">
									<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Price,'0'); ?>
								</span> 
								<?php
									$date = date("Y-m-d");
									if($NewProducts->products[$i]->Special_Price_From_Date !='' && $NewProducts->products[$i]->Special_Price_From_Date >= $date )
									{
										$date1=date_create($NewProducts->products[$i]->Special_Price_From_Date);
										$date2=date_create($NewProducts->products[$i]->Special_Price_To_Date);
										$diff=date_diff($date1,$date2);
										$sign = $diff->format("%R");
										$days = $diff->format("%a");
										if($sign == '+' && $days >= 0)
										{ ?>
											<span class="special-price"> <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Special_Price,'0'); ?> </span>
								 <?php 	}
									} else if($NewProducts->products[$i]->Special_Price_From_Date =='' && $NewProducts->products[$i]->Special_Price_To_Date =='' ){
								 ?>									
									<span class="special-price"> <?php  echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Special_Price,'0'); ?></span>
								<?php }
								}else { ?>
									<span class="regular-price">
										<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Price,'0'); ?>
									</span>
								<?php }	?>
								<?php 
									  if($NewProducts->products[$i]->Product_Unit != "")
									   echo " / ".$NewProducts->products[$i]->Product_Unit;
								?>
                            </div>
                          </li>
                    <?php
                                
                        }
                    ?>
                </ul>
            </div>
                
                <div class="item ">
                <ul class="row list_produtcs" id="products_items">
                  <?php
                        for($i=10;$i<15;$i++)
                        {
                     ?>
                            <li class="<?php echo $liClasses[$i]; ?>">
                            <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$NewProducts->products[$i]->request_path; ?>">
                                <img src="<?php echo $NewProducts->products[$i]->ImageURL; ?>" alt="msupply" width="170" height="235"/>
                            </a>
                            <!--<div><?php echo $NewProducts->products[$i]->Product_Name; ?></div>-->
                            <div class="hmptitleblock"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$NewProducts->products[$i]->request_path; ?>" class="hmptitle" title="<?php echo $NewProducts->products[$i]->Product_Name;  ?>"> <?php echo $NewProducts->products[$i]->Product_Name; ?></a></div>
                            <div class="price_tag wishlist_price">                                         
								<?php if($NewProducts->products[$i]->Special_Price !=''){ ?>	
								<span class="old-price">
									<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Price,'0'); ?>
								</span> 
								<?php
									$date = date("Y-m-d");
									if($NewProducts->products[$i]->Special_Price_From_Date !='' && $NewProducts->products[$i]->Special_Price_From_Date >= $date )
									{
										$date1=date_create($NewProducts->products[$i]->Special_Price_From_Date);
										$date2=date_create($NewProducts->products[$i]->Special_Price_To_Date);
										$diff=date_diff($date1,$date2);
										$sign = $diff->format("%R");
										$days = $diff->format("%a");
										if($sign == '+' && $days >= 0)
										{ ?>
											<span class="special-price"> <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Special_Price,'0'); ?> </span>
								 <?php 	}
									} else if($NewProducts->products[$i]->Special_Price_From_Date =='' && $NewProducts->products[$i]->Special_Price_To_Date =='' ){
								 ?>									
									<span class="special-price"> <?php  echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Special_Price,'0'); ?></span>
								<?php }
								}else { ?>
									<span class="regular-price">
										<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Price,'0'); ?>
									</span>
								<?php }	?>
								<?php 
									  if($NewProducts->products[$i]->Product_Unit != "")
									   echo " / ".$NewProducts->products[$i]->Product_Unit;
								?>
                            </div>
                          </li>
                    <?php
                                
                        }
                    ?>
                </ul>
            </div>
            </div>
			<a class="left carousel-control previous controllers" href="#myCarousel"  data-slide="prev"><i class="fa fa-angle-left"></i></a> <a class="right carousel-control next controllers" href="#myCarousel" data-slide="next"><i class="fa fa-angle-right"></i></a> 
		</div>
          <!-- products items section(New Arrivals) end here -->
		  
          <!-- products items section(Best Seller) starts here -->
          <div id="myCarousel2" class="carousel slide">
            <div id="products_lists_2" class="carousel-inner">
              <!-- carousel item active  starts here-->
              <div class="item active">
                <ul class="row list_produtcs" id="products_items">
                     <?php
                        for($i=0;$i<5;$i++)
                        {
                     ?>
                            <li class="<?php echo $liClasses[$i]; ?>">
                            <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$BestSellers->products[$i]->request_path; ?>">
                                <img src="<?php echo $BestSellers->products[$i]->ImageURL; ?>" alt="msupply" width="170" height="235"/>
                            </a>
                            <!--<div><?php echo $BestSellers->products[$i]->Product_Name; ?></div>-->
                            <div class="hmptitleblock"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$BestSellers->products[$i]->request_path; ?>" class="hmptitle" title="<?php echo $BestSellers->products[$i]->Product_Name;  ?>"> <?php echo $BestSellers->products[$i]->Product_Name; ?></a></div>
                           
                           
                           <div class="price_tag wishlist_price">                                         
								<?php if($BestSellers->products[$i]->Special_Price !=''){ ?>	
								<span class="old-price">
									<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Price,'0'); ?>
								</span> 
								<?php
									$date = date("Y-m-d");
									if($BestSellers->products[$i]->Special_Price_From_Date !='' && $BestSellers->products[$i]->Special_Price_From_Date >= $date )
									{
										$date1=date_create($BestSellers->products[$i]->Special_Price_From_Date);
										$date2=date_create($BestSellers->products[$i]->Special_Price_To_Date);
										$diff=date_diff($date1,$date2);
										$sign = $diff->format("%R");
										$days = $diff->format("%a");
										if($sign == '+' && $days >= 0)
										{ ?>
											<span class="special-price"> <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Special_Price,'0'); ?> </span>
								 <?php 	}
									} else if($BestSellers->products[$i]->Special_Price_From_Date =='' && $BestSellers->products[$i]->Special_Price_To_Date =='' ){
								 ?>									
									<span class="special-price"> <?php  echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Special_Price,'0'); ?></span>
								<?php }
								}else { ?>
									<span class="regular-price">
										<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Price,'0'); ?>
									</span>
								<?php }	?>
								<?php 
									  if($BestSellers->products[$i]->Product_Unit != "")
									   echo " / ".$BestSellers->products[$i]->Product_Unit;
								?>
                            </div>
                            
                           
                          </li>
                    <?php
                                
                        }
                    ?>
                </ul>
              </div>
              <!-- carousel item active  ends here-->
			  
              <!-- carousel item starts here -->
              <div class="item ">
                <ul class="row list_produtcs" id="products_items">
                    <?php
                        for($i=5;$i<10;$i++)
                        {
                    ?>
                            <li class="<?php echo $liClasses[$i]; ?>">
                            <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$BestSellers->products[$i]->request_path; ?>">
                                <img src="<?php echo $BestSellers->products[$i]->ImageURL; ?>" alt="msupply" width="170" height="235"/>
                            </a>
                            <!--<div><?php echo $BestSellers->products[$i]->Product_Name; ?></div>-->
                            <div class="hmptitleblock"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$BestSellers->products[$i]->request_path; ?>" class="hmptitle" title="<?php echo $BestSellers->products[$i]->Product_Name;  ?>"> <?php echo $BestSellers->products[$i]->Product_Name; ?></a></div>
                            <div class="price_tag wishlist_price">                                         
								<?php if($BestSellers->products[$i]->Special_Price !=''){ ?>	
								<span class="old-price">
									<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Price,'0'); ?>
								</span> 
								<?php
									$date = date("Y-m-d");
									if($BestSellers->products[$i]->Special_Price_From_Date !='' && $BestSellers->products[$i]->Special_Price_From_Date >= $date )
									{
										$date1=date_create($BestSellers->products[$i]->Special_Price_From_Date);
										$date2=date_create($BestSellers->products[$i]->Special_Price_To_Date);
										$diff=date_diff($date1,$date2);
										$sign = $diff->format("%R");
										$days = $diff->format("%a");
										if($sign == '+' && $days >= 0)
										{ ?>
											<span class="special-price"> <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Special_Price,'0'); ?> </span>
								 <?php 	}
									} else if($BestSellers->products[$i]->Special_Price_From_Date =='' && $BestSellers->products[$i]->Special_Price_To_Date =='' ){
								 ?>									
									<span class="special-price"> <?php  echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Special_Price,'0'); ?></span>
								<?php }
								}else { ?>
									<span class="regular-price">
										<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Price,'0'); ?>
									</span>
								<?php }	?>
								<?php 
									  if($BestSellers->products[$i]->Product_Unit != "")
									   echo " / ".$BestSellers->products[$i]->Product_Unit;
								?>
                            </div>
                          </li>
                    <?php
                                
                        }
                    ?>
                </ul>
              </div>
                <div class="item ">
                <ul class="row list_produtcs" id="products_items">
                    <?php
                        for($i=10;$i<15;$i++)
                        {
                     ?>
                            <li class="<?php echo $liClasses[$i]; ?>">
                            <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$BestSellers->products[$i]->request_path; ?>">
                                <img src="<?php echo $BestSellers->products[$i]->ImageURL; ?>" alt="msupply" width="170" height="235"/>
                            </a>
                            <!--<div><?php echo $BestSellers->products[$i]->Product_Name; ?></div>-->
                            <div class="hmptitleblock"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$BestSellers->products[$i]->request_path; ?>" class="hmptitle" title="<?php echo $BestSellers->products[$i]->Product_Name;  ?>"> <?php echo $BestSellers->products[$i]->Product_Name; ?></a></div>
                            <div class="price_tag wishlist_price">                                         
								<?php if($BestSellers->products[$i]->Special_Price !=''){ ?>	
								<span class="old-price">
									<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Price,'0'); ?>
								</span> 
								<?php
									$date = date("Y-m-d");
									if($BestSellers->products[$i]->Special_Price_From_Date !='' && $BestSellers->products[$i]->Special_Price_From_Date >= $date )
									{
										$date1=date_create($BestSellers->products[$i]->Special_Price_From_Date);
										$date2=date_create($BestSellers->products[$i]->Special_Price_To_Date);
										$diff=date_diff($date1,$date2);
										$sign = $diff->format("%R");
										$days = $diff->format("%a");
										if($sign == '+' && $days >= 0)
										{ ?>
											<span class="special-price"> <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Special_Price,'0'); ?> </span>
								 <?php 	}
									} else if($BestSellers->products[$i]->Special_Price_From_Date =='' && $BestSellers->products[$i]->Special_Price_To_Date =='' ){
								 ?>									
									<span class="special-price"> <?php  echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Special_Price,'0'); ?></span>
								<?php }
								}else { ?>
									<span class="regular-price">
										<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $BestSellers->products[$i]->Price,'0'); ?>
									</span>
								<?php }	?>
								<?php 
									  if($BestSellers->products[$i]->Product_Unit != "")
									   echo " / ".$BestSellers->products[$i]->Product_Unit;
								?>
                            </div>
                          </li>
                    <?php
                                
                        }
                    ?>
                </ul>
              </div>
              <!-- carousel item end here -->
            </div> <a class="left carousel-control previous controllers" href="#myCarousel2" data-slide="prev"><i class="fa fa-angle-left"></i></a> <a class="right carousel-control next controllers" href="#myCarousel2" data-slide="next"><i class="fa fa-angle-right"></i></a> </div>
          <!-- products items section(Best Seller) end here -->
          <?php
                $block = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('coming-soon');
                echo $block->getContent();
           ?>
        </div>
        <!-- msupply products  end here -->
 </div> 
 </div>
	 <!-- msupply products container end here -->
