<?php
$servieProviderTypes = array(
                            //"Apartment Association Representative",
                            "Architect",
                            "Carpentry Contractor",
                            "Civil Contractor",
                            "Civil Engineer",
                            //"Corporate Representative",
                            "Electrical Contractor",
                            "Flooring Contractor",
                            "Granite Layer",
                            "Home Automation Consultant",
                            "Interior Designer",
                            "Landscaping Contractor/Consultant",
                            "Legal Adviser",
                            "Masonry Contractor",
                            "Painting Contractor",
                            "Plumbing Contractor",
                            "Project Manager/Consultant/PMC",
                            "Tile Layer",
                            "Valuator",
                            "Others");
$defaultServiceProviderType = "Architect";

?>
<!--mSupply Service Providers start-->
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 whitebg">
  <div class="container">
    <div class="row">
      <div class="service">
          <h1>Become a Service Provider</h1>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pad0"><img src="<?php echo $this->getSkinUrl('images/service_01.jpg'); ?>" alt=""></div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pad0">
              <div class="service_box">
                <h4 class="black">Are you an architect, interior designer or contractor ?</h4>
                <h4>Many customers are looking for you.</h4>
				<form id="serviceproviderForm1" action="<?php echo $this->getUrl('serviceproviders/index/save'); ?>" method="post">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><input type="text" placeholder="Name" name="sp1name" id="sp1name" class="required-entry"/></div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><input type="text" placeholder="Phone" name="sp1phone" id="sp1phone" class="required-entry validate-digits validate-length maximum-length-10 minimum-length-10" /></div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                  <select name="sp1service" id="sp1service" class="required-entry" >
                    <?php
                        foreach($servieProviderTypes as $serviceProvider)
                        {
                    ?>
                          <option value="<?php echo $serviceProvider; ?>" <?php if($defaultServiceProviderType==$serviceProvider) echo ' selected '; ?>>
                            <?php echo $serviceProvider; ?>
                          </option>
                    <?php
                        }
                    ?>
                  </select>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pad0" id="others-container" style="display:none;"><input type="text" placeholder="If Others, please specify" name="sp1others" id="sp1others"  class="required-entry"/></div>
                <div class="col-xs-12 mt22 know-more-block" id="sp1"><button type="submit" class="know_more_btn col-xs-4">Register</button></div>
				</form>
				<div id="formSuccess2" style="display:none;color:#000;clear:both;"></div>
				<script type="text/javascript">
				//<![CDATA[
					var serviceproviderForm1 = new VarienForm('serviceproviderForm1', false);
				//]]>
 
				//<![CDATA[
					var formId2 = 'serviceproviderForm1';
					var myForm2 = new VarienForm(formId2, false);
					var postUrl2 = '<?php echo $this->getUrl('serviceproviders/index/save') ?>';
					var postapiUrl2 = '<?php echo $this->getUrl('serviceproviders/index/senddatatoadjetter') ?>';
					function doapicallAjax2() {
						jQuery('#formSuccess2').html('');					
						if (myForm2.validator.validate()) {
						jQuery('#sp1').html('');
						jQuery('#sp1').html('Please wait...');
						 if(jQuery("#sp1service").val() == "Others")
                         {
                             jQuery("#sp1service option:selected").val(jQuery("#sp1others").val());
                         }
							new Ajax.Updater(
								{ success:'formSuccess' }, postapiUrl2, {
									method:'post',
									asynchronous:true,
									evalScripts:false,
									onComplete:function(request, json) {
										
									},
									onLoading:function(request, json){
										Element.show('formLoader');
									},
									parameters: $(formId2).serialize(true),
								}
							);
						}
					}
					function doAjax2() {
						jQuery('#formSuccess2').html('');					
						if (myForm2.validator.validate()) {
						jQuery('#sp1').html('');
						jQuery('#sp1').html('Please wait...');
						 if(jQuery("#sp1service").val() == "Others")
                         {
                             jQuery("#sp1service option:selected").val(jQuery("#sp1others").val());
                         }
							new Ajax.Updater(
								{ success:'formSuccess' }, postUrl2, {
									method:'post',
									asynchronous:true,
									evalScripts:false,
									onComplete:function(request, json) {
										//Element.hide(formId);
										document.getElementById(formId2).reset();
										Element.show('formSuccess2');
										var div = document.getElementById('formSuccess2');
										jQuery('#formSuccess2').html('');
										div.innerHTML = div.innerHTML + 'Thank You. Our expert will contact you.';
										jQuery('#sp1').html('<button class="know_more_btn col-xs-4" type="submit">Register</button>');
										jQuery('#sp1name').val('');
										jQuery('#sp1phone').val('');
                                         jQuery("#sp1service option:last-child").val('Others');
										jQuery("#others-container").css('visibility','hidden');
                                         jQuery("#others-container").css('display','none');
										
									},
									onLoading:function(request, json){
										Element.show('formLoader');
									},
									parameters: $(formId2).serialize(true),
								}
							);
						}
					}
					
					new Event.observe(formId2, 'submit', function(e){
						e.stop();
						doapicallAjax2()
						doAjax2();
					});
                    
                    jQuery("#sp1service").change(function(){
                       if(jQuery(this).val() == "Others")
                       {
                           jQuery("#others-container").css('visibility','visible');
                           jQuery("#others-container").css('display','block');
                       }
                        else
                        {
                            
                           jQuery("#others-container").css('visibility','hidden');
                           jQuery("#others-container").css('display','none');
                        }
                    });
				//]]>
				</script>
				
              </div>
          </div>
          <div class="clearfix"></div>
           
           
      </div>
    </div>
  </div>
</div>
<!--mSupply Service Providers end-->
