
<?php
    $methods = $this->getMethods();
    $oneMethod = count($methods) <= 1;
?>
<?php if (empty($methods)): ?>
    <div>
        <?php echo $this->__('No Payment Methods') ?>
    </div>
<?php else:
    foreach ($methods as $_method):
        $_code = $_method->getCode();
?>


    <div>
    <?php if(!$oneMethod): ?>
        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
    <?php else: ?>
        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
        <?php $oneMethod = $_code; ?>
    <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
		
		<?php if($_code == "paymentmodulepackbankin"): ?>
		<div class="paymt-desc"><?php echo $this->__('On selecting this option a HDFC Bank Challan will be generated. Deposit the DD with challan in nearest HDFC Bank to confirm the order') ?></div>
		<?php endif; ?>
		<?php if($_code == "hdfc_standard"): ?>
		<div class="paymt-desc"><?php echo $this->__('On selecting this option you will redirected to HDFC payment gateway. Transaction charges of 2.05% would be applicable.') ?></div>
		<?php endif; ?>
		<?php if($_code == "paymentmodulepackdd_checkout"): ?>
		<div class="paymt-desc"><?php echo $this->__('On selecting this option a HDFC Bank Challan will be generated. Deposit the cash with challan in nearest HDFC Bank to confirm the order') ?></div>
		<?php endif; ?>
		<?php if($_code == "cashondelivery"): ?>
		<div class="paymt-desc"><?php echo $this->__('Cash Before Dispatch') ?></div>
		<?php endif; ?>
		<?php if($_code == "paymentmodulepack"): ?>
		<div class="paymt-desc"><?php echo $this->__('On selecting this option a HDFC Bank Challan will be generated. Deposit the cheque with challan in nearest HDFC Bank to confirm the order.') ?></div>
		<?php endif; ?>
	
    </div>

    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
    <div>
        <?php echo $html; ?>
    </div>
    <?php endif; ?>
<?php endforeach;
    endif;
?>
<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
    //<![CDATA[
    <?php echo $this->getChildChildHtml('scripts'); ?>
    payment.init();
    <?php if (is_string($oneMethod)): ?>
    payment.switchMethod('<?php echo $oneMethod ?>');
        <?php endif; ?>
    //]]>
</script>

<style>.form-list{width:100% !important;}</style>
